# Site settings
title:              "Vasco Fernandes blog"
email:              vasco.bailao@tecnico.ulisboa.pt
description: > # this means to ignore newlines until "baseurl:"
  Description goes here
baseurl:            ""
url:                "https://vascobailao.github.io"
twitter_username:   (Never!)
github_username:    vascobailao
future:             True

# Build settings
markdown:           kramdown
gems:               [jekyll-paginate]
paginate:           15
